name: chat_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  socket_io_client: ^3.1.2
  image_picker: ^1.1.2
  http: ^1.5.0
  path: ^1.9.1
  mime: ^2.0.0
  video_player: ^2.10.0
  record: ^6.1.2
  waveform_flutter: ^1.2.0
  audioplayers: ^6.5.1
  path_provider: ^2.1.5
  http_parser: ^4.1.2
  file_picker: ^10.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
